LMS_Assig/Controllers/AppRolesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Data;

namespace LMS_Assig_.Controllers
{
    [Authorize(Roles = "Admin")]
    public class AppRolesController : Controller
    {
        private readonly RoleManager<IdentityRole> _roleManager;


        public AppRolesController(RoleManager<IdentityRole> roleManager)
        {
            _roleManager = roleManager;

        }
        public IActionResult Index()
        {
            var roles = _roleManager.Roles;
            return View(roles);
        }

        [HttpGet]

        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]

        public async Task<IActionResult> Create(IdentityRole model)
        {
            //Avoiding Duplicates//Needs o learn from Sir. Waqas
            if (!_roleManager.RoleExistsAsync(model.Name).GetAwaiter().GetResult())
            {
                _roleManager.CreateAsync(new IdentityRole(model.Name)).GetAwaiter().GetResult();
            }
            return RedirectToAction("Index");
        }
    }
}

LMS_Assig/Controllers/FileController.cs
using LMS_Assig_.Data;
using LMS_Assig_.Models;
using LMS_Assig_.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Internal;
using NuGet.Protocol;
using System;
using System.Collections.Generic;
using System.Data;
using System.Drawing.Drawing2D;
using System.IO;
using System.Linq;
using System.Numerics;
using System.Security.Claims;
using System.Threading.Tasks;
using static System.Collections.Specialized.BitVector32;

namespace LMS_Assig_.Controllers
{
    
    public class FileController : Controller
    {
        

        private readonly UserManager<ApplicationUser> _userManager;
        private readonly ApplicationDbContext _context;
        public FileController(ApplicationDbContext context, 
            UserManager<ApplicationUser> userManager)
        {
            
             _context = context;
            _userManager = userManager; 
        }

        public async Task<IActionResult> Index()
        {
            var currentUser = _userManager.GetUserAsync(HttpContext.User).Result;
            return View(await _context.Assignment.Where(e => e.userId == currentUser.Id).ToListAsync());
        }

      
        [HttpGet]
        public async Task<IActionResult> Upload()
        {
             var currentUser = _userManager.GetUserAsync(HttpContext.User).Result;
            var UserId = currentUser.Id;
            var viewModel = new AssignmentViewModel();
            var sectionIds = _context.AssignSection
                .Where(a => a.Teacher == currentUser.Id)
                .ToList();
            
            foreach (var item in sectionIds)
            {
                var dt = _context.SectionDetails.Where(a => a.SectionId == item.SectionId).ToList();


                if(viewModel.SectionSelectList==null)
                    viewModel.SectionSelectList=dt;

                else
                    viewModel.SectionSelectList.AddRange(dt);


            }
           



            return View(viewModel);
        }
  
        [HttpPost]
        public async Task<IActionResult> Upload(IFormFile file, AssignmentViewModel viewModel)
        {
            viewModel.Assignment.Status = Status.upload;
            var currentUser = _userManager.GetUserAsync(HttpContext.User).Result;
            var UserId = currentUser.Id;
            viewModel.Assignment.userId = UserId;
            string filename = file.FileName;
            filename = Path.GetFileName(filename);

            // Check file type


            string[] allowedExtensions = { ".pdf", ".doc", ".docx", ".ppt", ".pptx", ".xls", ".xlsx", ".txt", ".txts" };
            string fileExtension = Path.GetExtension(filename);
            if (!allowedExtensions.Contains(fileExtension.ToLower()))
            {
                ViewBag.Message = "File type not allowed";
                return View();
            }


            string folderPath = Path.Combine(Directory.GetCurrentDirectory(), "UserFile");
            if (!Directory.Exists(folderPath))
            {
                Directory.CreateDirectory(folderPath);
            }
            string uploadpath = Path.Combine(folderPath, filename);
            using (var stream = new FileStream(uploadpath, FileMode.Create))
            {
                file.CopyToAsync(stream);
                viewModel.Assignment.FilePath= uploadpath;
                _context.Add(viewModel.Assignment);
                await _context.SaveChangesAsync();
            }
            return RedirectToAction("Index");


        }






        [Authorize(Roles = "Teacher")]
        public IActionResult Download(string fileName)
        {
            var filePath = Path.Combine(Directory.GetCurrentDirectory(), "UserFile", fileName);

            if (!System.IO.File.Exists(filePath))
            {
                return NotFound();
            }

            var fileStream = new FileStream(filePath, FileMode.Open, FileAccess.Read);

            return File(fileStream, "application/octet-stream", fileName);
        }

        public ActionResult ShowAssignments()
        {
            var vm = new AssignmentViewModel();
            vm.ApplicationUser = _userManager.GetUserAsync(HttpContext.User).Result;
            int sectionID = GetCurrentUserSectionID();
            vm.assignments = _context.Assignment.ToList();
           vm.FilterAssignments = vm.assignments.Where(a => a.SectionID == sectionID && a.Status==Status.upload).ToList();
            return View(vm);
        }

        private int GetCurrentUserSectionID()
        {
            var currentUser = _userManager.GetUserAsync(HttpContext.User).Result;

            if (currentUser != null)
            {
                var sectionId = currentUser.SectionId;

                if (sectionId == null)
                {
                    return 0;
                }
                // Default value or error handling if section ID is not valid
                return (int)sectionId;
            }

            // Default value or error handling if current user is not found
            return 0;
        }






































        public async Task<IActionResult> AnsFiles()
        {
            var currentUser = _userManager.GetUserAsync(HttpContext.User).Result;
            return View(await _context.Assignment.Where(e=>e.userId== currentUser.Id).ToListAsync());
        }





        [HttpGet]
        public async Task<IActionResult> UploadAnswer(int? id)
        {
            var currentUser = _userManager.GetUserAsync(HttpContext.User).Result;

            if (id == null || _context.Assignment == null)
            {
                return NotFound();
            }

            var assignments = await _context.Assignment.FindAsync(id);
           
            return View(assignments);
        }


       


        [HttpPost]
        public async Task<IActionResult> UploadAnswer(IFormFile file, int id)
        {
            if (id == null || _context.Assignment == null)
            {
                return NotFound();
            }

            var assignments = await _context.Assignment.FindAsync(id);
            if (assignments == null)
            {
                return NotFound();
            }
            var currentUser = _userManager.GetUserAsync(HttpContext.User).Result;
            Assignment assignment = new Assignment{
                assgnID = assignments.Id,
                Name = assignments.Name,
                SectionName = assignments.SectionName,
                UploadDate = DateTime.Now,
                SectionID = assignments.SectionID,
                Status = Status.submit,
                userId= currentUser.Id
            };

            


            // Save the uploaded file in the "Uploads" folder
            string filename = file.FileName;
            filename = Path.GetFileName(filename);

            // Check file type


            string[] allowedExtensions = { ".pdf", ".doc", ".docx", ".ppt", ".pptx", ".xls", ".xlsx", ".txt", ".txts" };
            string fileExtension = Path.GetExtension(filename);
            if (!allowedExtensions.Contains(fileExtension.ToLower()))
            {
                ViewBag.Message = "File type not allowed";
                return View();
            }
            // Save the uploaded file in the "Uploads" folder
            string folderPath = Path.Combine(Directory.GetCurrentDirectory(), "AwnserUserFile");
            if (!Directory.Exists(folderPath))
            {
                Directory.CreateDirectory(folderPath);
            }
            string uploadpath = Path.Combine(folderPath, filename);
            using (var stream = new FileStream(uploadpath, FileMode.Create))
            {
                file.CopyToAsync(stream);
                assignment.FilePath = uploadpath;
                _context.Add(assignment);
                await _context.SaveChangesAsync();
            }




            return RedirectToAction("AnsFiles");
        }
        public async Task<IActionResult> AllAnswer(int? id)
        {
            return View(await _context.Assignment.Where(e => e.assgnID == id).ToListAsync());
        }

    }
}

LMS_Assig/Controllers/SectionDetailsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using LMS_Assig_.Data;
using LMS_Assig_.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using LMS_Assig_.ViewModel;
using Microsoft.EntityFrameworkCore.Metadata.Internal;

namespace LMS_Assig_.Controllers
{
    //[Authorize(Roles = "Teacher")]
  

    public class SectionDetailsController : Controller
    {
       
        private readonly ApplicationDbContext _context;

        private readonly UserManager<ApplicationUser> _userManager;
        private readonly RoleManager<ApplicationUser> _roleManager;
        public SectionDetailsController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: SectionDetails
        public async Task<IActionResult> Index()
        {
              return _context.SectionDetails != null ? 
                          View(await _context.SectionDetails.ToListAsync()) :
                          Problem("Entity set 'ApplicationDbContext.SectionDetails'  is null.");
        }
        [Authorize(Roles = "Teacher")]
        // GET: SectionDetails/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.SectionDetails == null)
            {
                return NotFound();
            }

            var sectionDetails = await _context.SectionDetails
                .FirstOrDefaultAsync(m => m.SectionId == id);
            if (sectionDetails == null)
            {
                return NotFound();
            }

            return View(sectionDetails);
        }
        //[Authorize(Roles = "Teacher")]
        // GET: SectionDetails/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: SectionDetails/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("SectionId,Name,Title")] SectionDetails sectionDetails)
        {
            if (ModelState.IsValid)
            {
                _context.Add(sectionDetails);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(sectionDetails);
        }
        //[Authorize(Roles = "Teacher")]
        //[Authorize(Roles = "Student")]
        // GET: SectionDetails/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.SectionDetails == null)
            {
                return NotFound();
            }

            var sectionDetails = await _context.SectionDetails.FindAsync(id);
            if (sectionDetails == null)
            {
                return NotFound();
            }
            return View(sectionDetails);
        }

        // POST: SectionDetails/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("SectionId,Name,Title")] SectionDetails sectionDetails)
        {
            if (id != sectionDetails.SectionId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(sectionDetails);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SectionDetailsExists(sectionDetails.SectionId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(sectionDetails);
        }

        // GET: SectionDetails/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.SectionDetails == null)
            {
                return NotFound();
            }

            var sectionDetails = await _context.SectionDetails
                .FirstOrDefaultAsync(m => m.SectionId == id);
            if (sectionDetails == null)
            {
                return NotFound();
            }

            return View(sectionDetails);
        }

        // POST: SectionDetails/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.SectionDetails == null)
            {
                return Problem("Entity set 'ApplicationDbContext.SectionDetails'  is null.");
            }
            var sectionDetails = await _context.SectionDetails.FindAsync(id);
            if (sectionDetails != null)
            {
                _context.SectionDetails.Remove(sectionDetails);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SectionDetailsExists(int id)
        {
          return (_context.SectionDetails?.Any(e => e.SectionId == id)).GetValueOrDefault();
        }





        [HttpGet]
        //[Authorize(Roles = "Admin")]
        public async Task<IActionResult>  GrantSectionAccess()
        {
            var viewModel = new AssignSectionViewModel();
            viewModel.SectionSelectList = _context.SectionDetails.ToList();
            //viewModel.AssignSection = new AssignSection();

            viewModel.Teachers = await _userManager.Users.Where(o => o.Role == "Teacher").ToListAsync();


            return View(viewModel);
        }
        [HttpPost]
        //[Authorize(Roles = "Admin")]
        public async Task<IActionResult> GrantSectionAccess(AssignSection assignSection)
        {
            //var currentUser = _userManager.GetUserAsync(HttpContext.User).Result;
            assignSection.UserId= assignSection.Teacher;   
            if (ModelState!=null)
            {
                bool isAlreadyAssigned = await CheckIfTeacherIsAssigned(assignSection.Teacher, assignSection.SectionId);

                if (isAlreadyAssigned)
                {
                    ModelState.AddModelError("", "Teacher is already assigned to this section.");
                }
                else
                {
                    _context.Add(assignSection);
                    await _context.SaveChangesAsync();
                    return Redirect("index");
                }
            }

            // Refresh available sections
            return View(assignSection);
        }

        private async Task<bool> CheckIfTeacherIsAssigned(string teacherId, int sectionId)
        {
            var existingAssignment = await _context.AssignSection
                .FirstOrDefaultAsync(a => a.Teacher == teacherId && a.SectionId == sectionId);

            return existingAssignment != null;
        }



    }
}

LMS_Assig/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity;

@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LMS_Assig_</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/LMS_Assig_.styles.css" asp-append-version="true" />
</head>
<body>

@{
    @if (SignInManager.IsSignedIn(User))
    {
        var currentUser = SignInManager.UserManager.GetUserAsync(User).Result;
            var rolee = SignInManager.UserManager.GetUsersInRoleAsync("Admin");
            @if (currentUser.Role == "Admin")
        {
             <header>
                    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
                        <div class="container-fluid">
                            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">LMS_Assig_</a>
                            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                                    aria-expanded="false" aria-label="Toggle navigation">
                                <span class="navbar-toggler-icon"></span>
                            </button>
                            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                                <ul class="navbar-nav flex-grow-1">
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="AppRoles" asp-action="index">Roles</a>
                                    </li>

                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="SectionDetails" asp-action="index">Section's'</a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <partial name="_LoginPartial" />
                    </nav>
                </header>
        }
        else if(currentUser.Role=="Teacher")
        {
          
                <header>
                    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
                        <div class="container-fluid">
                            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">LMS_Assig_</a>
                            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                                    aria-expanded="false" aria-label="Toggle navigation">
                                <span class="navbar-toggler-icon"></span>
                            </button>
                            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                                <ul class="navbar-nav flex-grow-1">
                                 
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="File" asp-action="Index">Upload assignment</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="File" asp-action="ShowAssignments">Assignments</a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <partial name="_LoginPartial" />
                    </nav>
                </header>


            }
            else if (currentUser.Role == "Student")
            {
                <header>
                    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
                        <div class="container-fluid">
                            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">LMS_Assig_</a>
                            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                                    aria-expanded="false" aria-label="Toggle navigation">
                                <span class="navbar-toggler-icon"></span>
                            </button>
                            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                                <ul class="navbar-nav flex-grow-1">
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="File" asp-action="ShowAssignments">Assignments</a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <partial name="_LoginPartial" />
                    </nav>
                </header>
            }

        }
    else
    {
        <header>
                    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
                        <div class="container-fluid">
                            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">LMS_Assig_</a>
                            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                                    aria-expanded="false" aria-label="Toggle navigation">
                                <span class="navbar-toggler-icon"></span>
                            </button>
                            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                                <ul class="navbar-nav flex-grow-1">
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                                    </li>
                                   
                                </ul>
                            <ul class="navbar-nav">
                                @if (SignInManager.IsSignedIn(User))
                                {
                                    <li class="nav-item">
                                        <a id="manage" class="nav-link text-dark" asp-area="Identity" asp-page="/Account/Manage/Index" title="Manage">Hello @UserManager.GetUserName(User)!</a>
                                    </li>
                                    <li class="nav-item">
                                        <form id="logoutForm" class="form-inline" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })">
                                            <button id="logout" type="submit" class="nav-link btn btn-link text-dark">Logout</button>
                                        </form>
                                    </li>
                                }
                                else
                                {
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" id="register" asp-area="Identity" asp-page="/Account/Register">Register</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" id="login" asp-area="Identity" asp-page="/Account/Login">Login</a>
                                    </li>
                                }
                            </ul>
                            </div>
                        </div>
                    </nav>
        </header>
    }
  }
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - LMS_Assig_ - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>